Prueba2
JEdilbertoTC/bomberman pull request #2
Opened 2020-11-27 16:26 UTC by JocelynLlamas

2020-11-27 17:17 UTC, iuresti requested changes

2020-11-27 17:17 UTC, iuresti commented on Bomberman.java
> +            if(tocaVida()){
Se puede dar "tocarCalavera" y "tocarVida" al mismo tiempo? si no, considera utilizar `else if`

2020-11-27 17:17 UTC, iuresti commented on Bomberman.java
>      public void BombermanQuieto(){
los nombres de los métodos deben lowerCammelCase

2020-11-27 17:17 UTC, iuresti commented on Bomberman.java
>              Mundo.rola[0].pause();
los nombres de las variables deben ser lowerCammelCase

2020-11-27 17:17 UTC, iuresti commented on Bomberman.java
>              Mundo.rola[0].pause();
utiliza constantes para referirte a los índices de rola ... de modo que sepamos al leer el código que sonido se está pausando en esa línea

2020-11-27 17:17 UTC, iuresti commented on Bomberman.java
> +        Actor MCalavera;
los nombres de variables deben ser en lowerCammelCase

2020-11-27 17:17 UTC, iuresti commented on Bomberman.java
> +        Actor MCalavera;
qué significa "M" en "MCalavera" .. no utilicen abreviaciones

2020-11-27 17:17 UTC, iuresti commented on Bomberman.java
> +            detect = getWorld();
¿para qué estás utilizando la variable detect?

2020-11-27 17:17 UTC, iuresti commented on Bomberman.java
> +    public boolean tocaVida(){
tocaVida podría reescribirse como 
```
public boolean tocaVida(){
   return getOneObjectAtOffset(0,-10,MVida.class) != null;
}
```
lo mismo aplica para tocaCalavera

2020-11-27 17:33 UTC, JocelynLlamas commented on Bomberman.java
> +            if(tocaVida()){
No, serian las mejoras profe, asi que usare elseif 👍

2020-11-27 17:34 UTC, JocelynLlamas commented on Bomberman.java
> +        Actor MCalavera;
M es "Mejora", ok la vamos a renombrar uwu

2020-11-27 18:53 UTC, JEdilbertoTC commented on Bomberman.java
> +        Actor MCalavera;
Es qué hay una mejora llamada bomba pero es diferente a la bomba de bomberman y no supimos cómo llamar a la clase :c

2020-11-27 22:22 UTC, JocelynLlamas commented on Bomberman.java
> +            detect = getWorld();
Para checar que nuestro icono de mejora este dentro del mundo, estaría de más?

2020-11-27 22:23 UTC, JocelynLlamas commented on Bomberman.java
> +    public boolean tocaVida(){
Cierto gracias profe c:

2020-11-28 20:56 UTC, JEdilbertoTC approved these changes

2020-11-28 20:58 UTC, closed without merging