escritura en archivo .txt para las puntuaciones
JEdilbertoTC/bomberman pull request #3
Opened 2020-11-27 18:06 UTC by JEdilbertoTC

2020-11-27 20:02 UTC, iuresti requested changes

2020-11-27 20:02 UTC, iuresti commented on GameOver.java
> +        try
Cambia esto a try con recursos: https://picodotdev.github.io/blog-bitix/2018/04/la-sentencia-try-with-resources-de-java/

2020-11-27 20:02 UTC, iuresti commented on puntaje.txt
> +200
Elimina este archivo del commit y añádelo al .gitignore

2020-11-28 21:00 UTC, fakeghostl commented on GameOver.java
> +            fichero = new FileWriter("puntaje.txt");
Correccion:  fichero = new FileWriter("puntaje.txt",true);

2020-11-28 21:00 UTC, fakeghostl commented on puntaje.txt
> +200
Lo intente corregir con puntaje.txt y lo cambie a *.txt, igual sigue subiendose el archivo de texto.

2020-11-28 21:00 UTC, fakeghostl commented on GameOver.java
> +            fichero = new FileWriter("puntaje.txt");
Ya cambie eso, los nuevos commits

2020-11-28 21:00 UTC, merged